-- Takt Time independiente de colas y máquinas.
-- Ejecutar UNA sola vez en Supabase > SQL Editor.

create table if not exists public.takt_llegadas (
  id bigint generated by default as identity primary key,
  session_id uuid not null,
  numero_llegada integer not null,
  hora_llegada timestamptz not null,
  intervalo_segundos integer,
  created_at timestamptz not null default now(),
  unique (session_id, numero_llegada)
);

create index if not exists takt_llegadas_session_hora_idx
  on public.takt_llegadas (session_id, hora_llegada);

alter table public.takt_llegadas enable row level security;

-- No damos acceso directo a la tabla al navegador.
revoke all on table public.takt_llegadas from anon, authenticated;
revoke all on sequence public.takt_llegadas_id_seq from anon, authenticated;

-- Registrar una llegada dentro de una sesión privada.
create or replace function public.registrar_llegada_takt(p_session_id uuid)
returns table (
  id bigint,
  numero_llegada integer,
  hora_llegada timestamptz,
  intervalo_segundos integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_ahora timestamptz := clock_timestamp();
  v_anterior timestamptz;
  v_numero integer;
begin
  if p_session_id is null then
    raise exception 'session_id requerido';
  end if;

  -- Evita duplicados si se pulsa casi simultáneamente en la misma sesión.
  perform pg_advisory_xact_lock(hashtext(p_session_id::text));

  select max(t.numero_llegada), max(t.hora_llegada)
    into v_numero, v_anterior
  from public.takt_llegadas t
  where t.session_id = p_session_id;

  v_numero := coalesce(v_numero, 0) + 1;

  return query
  insert into public.takt_llegadas (
    session_id,
    numero_llegada,
    hora_llegada,
    intervalo_segundos
  ) values (
    p_session_id,
    v_numero,
    v_ahora,
    case
      when v_anterior is null then null
      else greatest(0, round(extract(epoch from (v_ahora - v_anterior)))::integer)
    end
  )
  returning
    takt_llegadas.id,
    takt_llegadas.numero_llegada,
    takt_llegadas.hora_llegada,
    takt_llegadas.intervalo_segundos;
end;
$$;

-- Devuelve únicamente los datos de la sesión cuyo UUID conoce el navegador.
create or replace function public.obtener_llegadas_takt(p_session_id uuid)
returns table (
  id bigint,
  numero_llegada integer,
  hora_llegada timestamptz,
  intervalo_segundos integer
)
language sql
security definer
set search_path = public
stable
as $$
  select t.id, t.numero_llegada, t.hora_llegada, t.intervalo_segundos
  from public.takt_llegadas t
  where t.session_id = p_session_id
  order by t.numero_llegada asc;
$$;

-- Permite borrar solo una sesión concreta desde el propio cronómetro.
create or replace function public.borrar_sesion_takt(p_session_id uuid)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_borrados integer;
begin
  delete from public.takt_llegadas
  where session_id = p_session_id;

  get diagnostics v_borrados = row_count;
  return v_borrados;
end;
$$;

grant execute on function public.registrar_llegada_takt(uuid) to anon, authenticated;
grant execute on function public.obtener_llegadas_takt(uuid) to anon, authenticated;
grant execute on function public.borrar_sesion_takt(uuid) to anon, authenticated;
